name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Configure fetch-depth to 0 if you need full history for some operations
        # with:
        #   fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your preferred Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Check README TOC consistency
        run: |
          # Run the 'toc' script to generate/update the TOC in README.md.
          # The 'doctoc' package should be installed as a devDependency and handled by 'npm ci'.
          npm run toc

          # Check if 'doctoc' made any changes to README.md.
          # 'git diff --exit-code' returns a non-zero exit code if there are differences.
          git diff --exit-code README.md || (echo "Error: README.md Table of Contents is not up to date. Please run 'npm run toc' locally and commit the changes." && exit 1)
        env:
          CI: true # Ensure CI environment is recognized, if needed by doctoc

      # Optional: Upload coverage to Codecov (only if enabled and token is provided)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info # Path to your lcov coverage file
        if: success() && secrets.CODECOV_TOKEN # Only run if previous steps succeeded and token exists